apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: meu-site
  name: meu-site-hpa
  labels:
    app: meu-site
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meu-site
  minReplicas: 5
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
    - type: ContainerResource
      containerResource:
        container: meu-site
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
    - type: ContainerResource
      containerResource:
        container: meu-site
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10
