apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-site-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: altaria.henriqzimer.com.br
    path: /mnt/altaria/kubernetes/meu-site-db-data
  mountOptions:
    - vers=4.1
    - hard
    - intr